version: "3"
services:
  api:
    container_name: api-container
    build: .
    image: node:12
    working_dir: /usr/src/address-api
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    environment: 
      # - MONGO_URL=mongodb://mongo:27017/clean-ts-api
    volumes:
      - ./dist/:/usr/src/address-api/dist/
      -./package.json:/usr/src/address-api/package.json
    ports:
      - "5050:5050"